### ISSUE TITLE
Stop to work

### ISSUE THREAD

**Issue by Rafes96** [User5842/udemy-reset#1]
Hi brother,
I've try to use, but no work, show error in console in fuction foreach. Can you fix it?
I would even make a pull request but I'm still noob in js
aaah, and sry my english, i try b better

`VM1283:1 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at <anonymous>:1:501
    at NodeList.forEach (<anonymous>)
    at t (<anonymous>:1:265)
    at <anonymous>:1:625`

**Comment by User5842** [comment]
Hey! Apologies for the delay. I got to this after someone else reported the same issue on Reddit. I'll get to it now.
